// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PRN_Project.Models;

#nullable disable

namespace PRN_Project.Migrations
{
    [DbContext(typeof(LmsDbContext))]
    [Migration("20251114132741_InitData2")]
    partial class InitData2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PRN_Project.Models.Account", b =>
                {
                    b.Property<int>("AId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("AId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            AId = 1,
                            Email = "admin@example.com",
                            Password = "Admin@123",
                            Role = 0,
                            Status = true
                        },
                        new
                        {
                            AId = 2,
                            Email = "teacher@example.com",
                            Password = "Teacher@123",
                            Role = 1,
                            Status = true
                        },
                        new
                        {
                            AId = 3,
                            Email = "student@example.com",
                            Password = "Student@123",
                            Role = 2,
                            Status = true
                        },
                        new
                        {
                            AId = 4,
                            Email = "student2@example.com",
                            Password = "Student@123",
                            Role = 2,
                            Status = true
                        });
                });

            modelBuilder.Entity("PRN_Project.Models.Admin", b =>
                {
                    b.Property<int>("AdId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdId"));

                    b.Property<int>("AId")
                        .HasColumnType("int");

                    b.Property<string>("AdName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("AdId");

                    b.HasIndex("AId")
                        .IsUnique();

                    b.ToTable("Admins");

                    b.HasData(
                        new
                        {
                            AdId = 1,
                            AId = 1,
                            AdName = "Super Admin"
                        });
                });

            modelBuilder.Entity("PRN_Project.Models.Answer", b =>
                {
                    b.Property<int>("AwId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AwId"));

                    b.Property<string>("AnswerContent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("EId")
                        .HasColumnType("int");

                    b.Property<bool?>("Status")
                        .HasColumnType("bit");

                    b.HasKey("AwId");

                    b.HasIndex("EId");

                    b.ToTable("Answers");

                    b.HasData(
                        new
                        {
                            AwId = 1,
                            AnswerContent = "[\r\n                        { \"Question\": \"What is 2 + 2?\", \"Options\": [\"3\", \"4\", \"5\", \"6\"], \"CorrectAnswer\": \"4\" },\r\n                        { \"Question\": \"What is 10 / 2?\", \"Options\": [\"2\", \"5\", \"10\", \"20\"], \"CorrectAnswer\": \"5\" }\r\n                    ]",
                            CreatedAt = new DateTime(2025, 1, 3, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            EId = 1,
                            Status = true
                        },
                        new
                        {
                            AwId = 2,
                            AnswerContent = "[\r\n                        { \"Question\": \"He ___ to school every day.\", \"Options\": [\"go\", \"goes\", \"going\", \"gone\"], \"CorrectAnswer\": \"goes\" },\r\n                        { \"Question\": \"Which word is a noun?\", \"Options\": [\"run\", \"beautiful\", \"happiness\", \"quickly\"], \"CorrectAnswer\": \"happiness\" }\r\n                    ]",
                            CreatedAt = new DateTime(2025, 1, 5, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            EId = 2,
                            Status = true
                        });
                });

            modelBuilder.Entity("PRN_Project.Models.AssignmentSubmission", b =>
                {
                    b.Property<int>("SubmissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubmissionId"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Grade")
                        .HasColumnType("float");

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.Property<int>("Sid")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SubmitTime")
                        .HasColumnType("datetime2");

                    b.HasKey("SubmissionId");

                    b.HasIndex("PostId");

                    b.HasIndex("Sid");

                    b.ToTable("AssignmentSubmissions");
                });

            modelBuilder.Entity("PRN_Project.Models.ChatGroup", b =>
                {
                    b.Property<int>("GroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GroupId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("GroupId");

                    b.ToTable("ChatGroups");

                    b.HasData(
                        new
                        {
                            GroupId = 3,
                            CreatedAt = new DateTime(2025, 11, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "CongDong",
                            Type = 1
                        });
                });

            modelBuilder.Entity("PRN_Project.Models.ChatMessage2", b =>
                {
                    b.Property<long>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("MessageId"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("GroupId")
                        .HasColumnType("int");

                    b.Property<int?>("ReceiverId")
                        .HasColumnType("int");

                    b.Property<int>("SenderId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("MessageId");

                    b.HasIndex("GroupId");

                    b.HasIndex("ReceiverId");

                    b.HasIndex("SenderId");

                    b.ToTable("ChatMessages2");
                });

            modelBuilder.Entity("PRN_Project.Models.Classroom", b =>
                {
                    b.Property<int>("ClassroomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClassroomId"));

                    b.Property<string>("ClassCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ClassDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Tid")
                        .HasColumnType("int");

                    b.HasKey("ClassroomId");

                    b.HasIndex("ClassCode")
                        .IsUnique();

                    b.HasIndex("Tid");

                    b.ToTable("Classrooms");
                });

            modelBuilder.Entity("PRN_Project.Models.ClassroomMember", b =>
                {
                    b.Property<int>("MemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MemberId"));

                    b.Property<int>("ClassroomId")
                        .HasColumnType("int");

                    b.Property<DateTime>("JoinDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Sid")
                        .HasColumnType("int");

                    b.HasKey("MemberId");

                    b.HasIndex("Sid");

                    b.HasIndex("ClassroomId", "Sid")
                        .IsUnique();

                    b.ToTable("ClassroomMembers");
                });

            modelBuilder.Entity("PRN_Project.Models.Comment", b =>
                {
                    b.Property<int>("CommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CommentId"));

                    b.Property<int>("Aid")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.HasKey("CommentId");

                    b.HasIndex("Aid");

                    b.HasIndex("PostId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("PRN_Project.Models.Exam", b =>
                {
                    b.Property<int>("EId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("EName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExamContent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<int?>("SuId")
                        .HasColumnType("int");

                    b.HasKey("EId");

                    b.HasIndex("SuId");

                    b.ToTable("Exams");

                    b.HasData(
                        new
                        {
                            EId = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            EName = "Math Midterm Exam",
                            EndTime = new DateTime(2025, 1, 2, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            ExamContent = "[\r\n                        { \"Question\": \"What is 2 + 2?\", \"Options\": [\"3\", \"4\", \"5\", \"6\"], \"CorrectAnswer\": \"4\" },\r\n                        { \"Question\": \"What is 10 / 2?\", \"Options\": [\"2\", \"5\", \"10\", \"20\"], \"CorrectAnswer\": \"5\" }\r\n                    ]",
                            StartTime = new DateTime(2025, 1, 2, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = true,
                            SuId = 1
                        },
                        new
                        {
                            EId = 2,
                            CreatedAt = new DateTime(2025, 1, 3, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            EName = "English Grammar Test",
                            EndTime = new DateTime(2025, 1, 4, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            ExamContent = "[\r\n                        { \"Question\": \"He ___ to school every day.\", \"Options\": [\"go\", \"goes\", \"going\", \"gone\"], \"CorrectAnswer\": \"goes\" },\r\n                        { \"Question\": \"Which word is a noun?\", \"Options\": [\"run\", \"beautiful\", \"happiness\", \"quickly\"], \"CorrectAnswer\": \"happiness\" }\r\n                    ]",
                            StartTime = new DateTime(2025, 1, 4, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = true,
                            SuId = 2
                        });
                });

            modelBuilder.Entity("PRN_Project.Models.ExamRank", b =>
                {
                    b.Property<int>("ErId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ErId"));

                    b.Property<int>("RaId")
                        .HasColumnType("int");

                    b.Property<int>("SuId")
                        .HasColumnType("int");

                    b.HasKey("ErId");

                    b.HasIndex("RaId");

                    b.HasIndex("SuId", "RaId")
                        .IsUnique();

                    b.ToTable("ExamRanks");

                    b.HasData(
                        new
                        {
                            ErId = 1,
                            RaId = 1,
                            SuId = 1
                        },
                        new
                        {
                            ErId = 2,
                            RaId = 2,
                            SuId = 2
                        });
                });

            modelBuilder.Entity("PRN_Project.Models.GroupMember", b =>
                {
                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("GroupId", "AccountId");

                    b.HasIndex("AccountId");

                    b.ToTable("GroupMembers");
                });

            modelBuilder.Entity("PRN_Project.Models.LearningMaterial", b =>
                {
                    b.Property<int>("MaterialID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaterialID"));

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("FilePath")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("SubjectID")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UploadDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("MaterialID");

                    b.HasIndex("SubjectID");

                    b.ToTable("LearningMaterials");
                });

            modelBuilder.Entity("PRN_Project.Models.Notification", b =>
                {
                    b.Property<int>("NtId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NtId"));

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SenderId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SentTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("NtId");

                    b.HasIndex("SenderId");

                    b.ToTable("Notifications");

                    b.HasData(
                        new
                        {
                            NtId = 1,
                            Content = "We’re excited to have you here!",
                            SenderId = 1,
                            SentTime = new DateTime(2025, 1, 5, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Welcome to the LMS System"
                        },
                        new
                        {
                            NtId = 2,
                            Content = "Don't forget your math exam this Friday at 8:00 AM.",
                            SenderId = 2,
                            SentTime = new DateTime(2025, 1, 7, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Upcoming Math Exam Reminder"
                        },
                        new
                        {
                            NtId = 3,
                            Content = "LMS will be under maintenance this weekend.",
                            SenderId = 1,
                            SentTime = new DateTime(2025, 1, 8, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "System Maintenance"
                        });
                });

            modelBuilder.Entity("PRN_Project.Models.NotificationReceiver", b =>
                {
                    b.Property<int>("NrId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NrId"));

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<int>("NtId")
                        .HasColumnType("int");

                    b.Property<int>("ReceiverId")
                        .HasColumnType("int");

                    b.HasKey("NrId");

                    b.HasIndex("NtId");

                    b.HasIndex("ReceiverId");

                    b.ToTable("NotificationReceivers");

                    b.HasData(
                        new
                        {
                            NrId = 1,
                            IsRead = true,
                            NtId = 1,
                            ReceiverId = 3
                        },
                        new
                        {
                            NrId = 2,
                            IsRead = false,
                            NtId = 1,
                            ReceiverId = 4
                        },
                        new
                        {
                            NrId = 3,
                            IsRead = false,
                            NtId = 2,
                            ReceiverId = 3
                        },
                        new
                        {
                            NrId = 4,
                            IsRead = true,
                            NtId = 3,
                            ReceiverId = 2
                        });
                });

            modelBuilder.Entity("PRN_Project.Models.Post", b =>
                {
                    b.Property<int>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PostId"));

                    b.Property<int>("Aid")
                        .HasColumnType("int");

                    b.Property<int>("ClassroomId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PostType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PostId");

                    b.HasIndex("Aid");

                    b.HasIndex("ClassroomId");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("PRN_Project.Models.PrivateChat", b =>
                {
                    b.Property<int>("ChatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChatId"));

                    b.Property<DateTime>("LastActive")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserAId")
                        .HasColumnType("int");

                    b.Property<int>("UserBId")
                        .HasColumnType("int");

                    b.HasKey("ChatId");

                    b.HasIndex("UserAId");

                    b.HasIndex("UserBId");

                    b.ToTable("PrivateChats");
                });

            modelBuilder.Entity("PRN_Project.Models.Rank", b =>
                {
                    b.Property<int>("RaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RaId"));

                    b.Property<float?>("MaxScore")
                        .HasColumnType("real");

                    b.Property<float?>("MinScore")
                        .HasColumnType("real");

                    b.Property<string>("RankName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RaId");

                    b.ToTable("Ranks");

                    b.HasData(
                        new
                        {
                            RaId = 1,
                            MaxScore = 10f,
                            MinScore = 8.5f,
                            RankName = "A"
                        },
                        new
                        {
                            RaId = 2,
                            MaxScore = 8.4f,
                            MinScore = 6.5f,
                            RankName = "B"
                        },
                        new
                        {
                            RaId = 3,
                            MaxScore = 6.4f,
                            MinScore = 4.5f,
                            RankName = "C"
                        },
                        new
                        {
                            RaId = 4,
                            MaxScore = 4.4f,
                            MinScore = 0f,
                            RankName = "D"
                        });
                });

            modelBuilder.Entity("PRN_Project.Models.Student", b =>
                {
                    b.Property<int>("SId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SId"));

                    b.Property<int>("AId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Dob")
                        .HasColumnType("datetime2");

                    b.Property<string>("Gender")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("SId");

                    b.HasIndex("AId")
                        .IsUnique();

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            SId = 1,
                            AId = 3,
                            Dob = new DateTime(2008, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gender = "Female",
                            SName = "Tran Thi C"
                        },
                        new
                        {
                            SId = 2,
                            AId = 4,
                            Dob = new DateTime(2008, 6, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gender = "Male",
                            SName = "Le Van D"
                        });
                });

            modelBuilder.Entity("PRN_Project.Models.Subject", b =>
                {
                    b.Property<int>("SuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SuId"));

                    b.Property<string>("SuName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("SuId");

                    b.HasIndex("SuId")
                        .IsUnique();

                    b.ToTable("Subjects");

                    b.HasData(
                        new
                        {
                            SuId = 1,
                            SuName = "Mathematics"
                        },
                        new
                        {
                            SuId = 2,
                            SuName = "English"
                        });
                });

            modelBuilder.Entity("PRN_Project.Models.Submit", b =>
                {
                    b.Property<int>("SbId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SbId"));

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EId")
                        .HasColumnType("int");

                    b.Property<int>("SId")
                        .HasColumnType("int");

                    b.Property<double?>("Score")
                        .HasColumnType("float");

                    b.Property<DateTime>("SubmitTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("SbId");

                    b.HasIndex("EId");

                    b.HasIndex("SId");

                    b.ToTable("Submits");

                    b.HasData(
                        new
                        {
                            SbId = 1,
                            Comment = "Good performance",
                            Content = "[{\"QuestionIndex\":1,\"ChosenAnswer\":\"4\"},{\"QuestionIndex\":2,\"ChosenAnswer\":\"5\"}]",
                            EId = 1,
                            SId = 1,
                            Score = 9.0,
                            SubmitTime = new DateTime(2025, 1, 4, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            SbId = 2,
                            Comment = "Needs to improve grammar",
                            Content = "[{\"QuestionIndex\":1,\"ChosenAnswer\":\"goes\"},{\"QuestionIndex\":2,\"ChosenAnswer\":\"run\"}]",
                            EId = 2,
                            SId = 2,
                            Score = 7.5,
                            SubmitTime = new DateTime(2025, 1, 6, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("PRN_Project.Models.Teacher", b =>
                {
                    b.Property<int>("TId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TId"));

                    b.Property<int>("AId")
                        .HasColumnType("int");

                    b.Property<string>("Qualification")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("TId");

                    b.HasIndex("AId")
                        .IsUnique();

                    b.ToTable("Teachers");

                    b.HasData(
                        new
                        {
                            TId = 1,
                            AId = 2,
                            Qualification = "Master of Mathematics",
                            TName = "Nguyen Van B"
                        });
                });

            modelBuilder.Entity("PRN_Project.Models.TeacherSubject", b =>
                {
                    b.Property<int>("TsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TsId"));

                    b.Property<int>("SuId")
                        .HasColumnType("int");

                    b.Property<int>("TId")
                        .HasColumnType("int");

                    b.HasKey("TsId");

                    b.HasIndex("SuId");

                    b.HasIndex("TId", "SuId")
                        .IsUnique();

                    b.ToTable("TeacherSubjects");

                    b.HasData(
                        new
                        {
                            TsId = 1,
                            SuId = 1,
                            TId = 1
                        },
                        new
                        {
                            TsId = 2,
                            SuId = 2,
                            TId = 1
                        });
                });

            modelBuilder.Entity("PRN_Project.Models.Admin", b =>
                {
                    b.HasOne("PRN_Project.Models.Account", "Account")
                        .WithOne("Admin")
                        .HasForeignKey("PRN_Project.Models.Admin", "AId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("PRN_Project.Models.Answer", b =>
                {
                    b.HasOne("PRN_Project.Models.Exam", "Exam")
                        .WithMany("Answers")
                        .HasForeignKey("EId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exam");
                });

            modelBuilder.Entity("PRN_Project.Models.AssignmentSubmission", b =>
                {
                    b.HasOne("PRN_Project.Models.Post", "Post")
                        .WithMany("Submissions")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PRN_Project.Models.Student", "Student")
                        .WithMany("Submissions")
                        .HasForeignKey("Sid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("PRN_Project.Models.ChatMessage2", b =>
                {
                    b.HasOne("PRN_Project.Models.ChatGroup", "Group")
                        .WithMany("Messages")
                        .HasForeignKey("GroupId");

                    b.HasOne("PRN_Project.Models.Account", "Receiver")
                        .WithMany()
                        .HasForeignKey("ReceiverId");

                    b.HasOne("PRN_Project.Models.Account", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("Receiver");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("PRN_Project.Models.Classroom", b =>
                {
                    b.HasOne("PRN_Project.Models.Teacher", "Teacher")
                        .WithMany("Classrooms")
                        .HasForeignKey("Tid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("PRN_Project.Models.ClassroomMember", b =>
                {
                    b.HasOne("PRN_Project.Models.Classroom", "Classroom")
                        .WithMany("Members")
                        .HasForeignKey("ClassroomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PRN_Project.Models.Student", "Student")
                        .WithMany("ClassroomMembers")
                        .HasForeignKey("Sid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Classroom");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("PRN_Project.Models.Comment", b =>
                {
                    b.HasOne("PRN_Project.Models.Account", "Account")
                        .WithMany("Comments")
                        .HasForeignKey("Aid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PRN_Project.Models.Post", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("PRN_Project.Models.Exam", b =>
                {
                    b.HasOne("PRN_Project.Models.Subject", "Subject")
                        .WithMany("Exams")
                        .HasForeignKey("SuId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("PRN_Project.Models.ExamRank", b =>
                {
                    b.HasOne("PRN_Project.Models.Rank", "Rank")
                        .WithMany("ExamRanks")
                        .HasForeignKey("RaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PRN_Project.Models.Submit", "Submit")
                        .WithMany("ExamRank")
                        .HasForeignKey("SuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rank");

                    b.Navigation("Submit");
                });

            modelBuilder.Entity("PRN_Project.Models.GroupMember", b =>
                {
                    b.HasOne("PRN_Project.Models.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PRN_Project.Models.ChatGroup", "Group")
                        .WithMany("Members")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("PRN_Project.Models.LearningMaterial", b =>
                {
                    b.HasOne("PRN_Project.Models.Subject", "Subject")
                        .WithMany("LearningMaterials")
                        .HasForeignKey("SubjectID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("PRN_Project.Models.Notification", b =>
                {
                    b.HasOne("PRN_Project.Models.Account", "Sender")
                        .WithMany("SentNotifications")
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("PRN_Project.Models.NotificationReceiver", b =>
                {
                    b.HasOne("PRN_Project.Models.Notification", "Notification")
                        .WithMany("Receivers")
                        .HasForeignKey("NtId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PRN_Project.Models.Account", "Receiver")
                        .WithMany("NotificationReceivers")
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Notification");

                    b.Navigation("Receiver");
                });

            modelBuilder.Entity("PRN_Project.Models.Post", b =>
                {
                    b.HasOne("PRN_Project.Models.Account", "Account")
                        .WithMany("Posts")
                        .HasForeignKey("Aid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PRN_Project.Models.Classroom", "Classroom")
                        .WithMany("Posts")
                        .HasForeignKey("ClassroomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Classroom");
                });

            modelBuilder.Entity("PRN_Project.Models.PrivateChat", b =>
                {
                    b.HasOne("PRN_Project.Models.Account", "UserA")
                        .WithMany()
                        .HasForeignKey("UserAId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PRN_Project.Models.Account", "UserB")
                        .WithMany()
                        .HasForeignKey("UserBId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UserA");

                    b.Navigation("UserB");
                });

            modelBuilder.Entity("PRN_Project.Models.Student", b =>
                {
                    b.HasOne("PRN_Project.Models.Account", "Account")
                        .WithOne("Student")
                        .HasForeignKey("PRN_Project.Models.Student", "AId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("PRN_Project.Models.Submit", b =>
                {
                    b.HasOne("PRN_Project.Models.Exam", "Exam")
                        .WithMany("Submits")
                        .HasForeignKey("EId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PRN_Project.Models.Student", "Student")
                        .WithMany("Submits")
                        .HasForeignKey("SId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exam");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("PRN_Project.Models.Teacher", b =>
                {
                    b.HasOne("PRN_Project.Models.Account", "Account")
                        .WithOne("Teacher")
                        .HasForeignKey("PRN_Project.Models.Teacher", "AId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("PRN_Project.Models.TeacherSubject", b =>
                {
                    b.HasOne("PRN_Project.Models.Subject", "Subject")
                        .WithMany("TeacherSubjects")
                        .HasForeignKey("SuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PRN_Project.Models.Teacher", "Teacher")
                        .WithMany("TeacherSubjects")
                        .HasForeignKey("TId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subject");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("PRN_Project.Models.Account", b =>
                {
                    b.Navigation("Admin");

                    b.Navigation("Comments");

                    b.Navigation("NotificationReceivers");

                    b.Navigation("Posts");

                    b.Navigation("SentNotifications");

                    b.Navigation("Student");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("PRN_Project.Models.ChatGroup", b =>
                {
                    b.Navigation("Members");

                    b.Navigation("Messages");
                });

            modelBuilder.Entity("PRN_Project.Models.Classroom", b =>
                {
                    b.Navigation("Members");

                    b.Navigation("Posts");
                });

            modelBuilder.Entity("PRN_Project.Models.Exam", b =>
                {
                    b.Navigation("Answers");

                    b.Navigation("Submits");
                });

            modelBuilder.Entity("PRN_Project.Models.Notification", b =>
                {
                    b.Navigation("Receivers");
                });

            modelBuilder.Entity("PRN_Project.Models.Post", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Submissions");
                });

            modelBuilder.Entity("PRN_Project.Models.Rank", b =>
                {
                    b.Navigation("ExamRanks");
                });

            modelBuilder.Entity("PRN_Project.Models.Student", b =>
                {
                    b.Navigation("ClassroomMembers");

                    b.Navigation("Submissions");

                    b.Navigation("Submits");
                });

            modelBuilder.Entity("PRN_Project.Models.Subject", b =>
                {
                    b.Navigation("Exams");

                    b.Navigation("LearningMaterials");

                    b.Navigation("TeacherSubjects");
                });

            modelBuilder.Entity("PRN_Project.Models.Submit", b =>
                {
                    b.Navigation("ExamRank");
                });

            modelBuilder.Entity("PRN_Project.Models.Teacher", b =>
                {
                    b.Navigation("Classrooms");

                    b.Navigation("TeacherSubjects");
                });
#pragma warning restore 612, 618
        }
    }
}
